"""
Django settings for gestor_fila_hulw project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from django.utils.translation import gettext_lazy as _
from django.urls import reverse_lazy
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

API_BASE_URL = "http://127.0.0.1:8000/api/v1"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-339&&s55h9xja8$*x@-p^j)%3hm4wo&=ms)q)1(de7)35zw*j+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

SIMPLE_HISTORY_REVERT_DISABLED = True

# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.forms',
    'unfold.contrib.filters',
    'unfold.contrib.simple_history',
    
    'simple_history',

    'fila_cirurgica',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'simple_history.middleware.HistoryRequestMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

ROOT_URLCONF = 'gestor_fila_hulw.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gestor_fila_hulw.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'd592fj7ir1fa99',
    #     'USER': 'udker5tm8iheud',
    #     'PASSWORD': 'pc6351ca886fb5c47681cef34bfaa650c99ddea70bc3912513d36210ac760c7ff',
    #     'HOST': 'casrkuuedp6an1.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com',
    #     'PORT': '5432',
    # }
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'localhost_lechulw',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "pt-br"

LOCALE_PATHS = [BASE_DIR / 'locale']

LANGUAGES = (
    ("en", _("Inglês")),
    ("pt-br", _("Português (Brasil)")),
)

TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# UNFOLD CONFIGURATION
# -----------------------------------------------------------------------------
def environment_callback(request):
    """
    Função para exibir um indicador de ambiente (Desenvolvimento/Produção).
    Retorna uma tupla com o texto e a cor. Cores disponíveis:
    "info", "danger", "warning", "success"
    """
    if DEBUG:
        return [_("Desenvolvimento"), "warning"]
    return [_("Produção"), "success"]

UNFOLD = {
    # --- Identidade do Site ---
    "SITE_TITLE": "Gestor de Fila Cirúrgica",
    "SITE_HEADER": "Gestor de Fila - HULW",
    "SITE_URL": reverse_lazy("admin:index"),
    # "SITE_SYMBOL": "health_and_safety",  # Ícone do Google Fonts
    "SITE_SYMBOL": "assignment_add",

    # --- Logo e Favicon (descomente e adicione seus arquivos em 'static/') ---
    # "SITE_LOGO": {
    #     "light": lambda request: static("logo-light.svg"),
    #     "dark": lambda request: static("logo-dark.svg"),
    # },
    # "SITE_FAVICONS": [
    #     {
    #         "rel": "icon",
    #         "sizes": "32x32",
    #         "type": "image/svg+xml",
    #         "href": lambda request: static("favicon.svg"),
    #     },
    # ],

    # --- Funcionalidades e Aparência ---
    "SHOW_HISTORY": True,  # Mostra o botão "Histórico" (requer simple_history)
    "SHOW_VIEW_ON_SITE": False,  # Esconde o botão "Ver no site"
    "ENVIRONMENT": environment_callback, # Mostra o ambiente atual (Dev/Prod)
    "SHOW_LANGUAGES": True, # Mostra o seletor de idiomas

    # --- Barra Lateral (Sidebar) ---
    "SIDEBAR": {
        "show_search": True,  # Habilita a busca na barra lateral
        "show_all_applications": True, # Mostra todas as apps em um dropdown
    },

    # --- Estilos e Scripts Personalizados (descomente para usar) ---
    # "STYLES": [
    #     lambda request: static("css/custom_admin.css"),
    # ],
    # "SCRIPTS": [
    #     lambda request: static("js/custom_admin.js"),
    # ],
}