# Generated by Django 5.1.3 on 2024-12-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('prontuario', models.CharField(max_length=20, unique=True)),
                ('telefone_contato', models.CharField(blank=True, max_length=15, null=True)),
                ('telefone_contato2', models.CharField(blank=True, max_length=15, null=True)),
                ('nome_responsavel', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
            },
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=255)),
                ('origem', models.TextField()),
                ('complexidade', models.CharField(max_length=100)),
                ('modalidades', models.TextField()),
                ('instrumento_registro', models.CharField(max_length=255)),
                ('tipo_financiamento', models.CharField(max_length=255)),
                ('valor_ambulatorial_sa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_ambulatorial_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_hospitalar_sp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_hospitalar_sh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_hospitalar_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('atributo_complementar', models.JSONField(default=list)),
                ('sexo', models.CharField(max_length=50)),
                ('idade_minima', models.IntegerField()),
                ('idade_maxima', models.IntegerField()),
                ('quantidade_maxima', models.IntegerField()),
                ('media_permanencia', models.IntegerField()),
                ('pontos', models.IntegerField()),
                ('cbo', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Procedimento',
                'verbose_name_plural': 'Procedimentos',
                'ordering': ['codigo'],
            },
        ),
    ]
