# Generated by Django 5.1.3 on 2024-12-09 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila_cirurgica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='prontuario',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome_responsavel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do responsável'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone_contato',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone para contato principal'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone_contato2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone para contato secundário'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='atributo_complementar',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='cbo',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='complexidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='idade_maxima',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='idade_minima',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='instrumento_registro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='media_permanencia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='modalidades',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='origem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='pontos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='quantidade_maxima',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='sexo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='tipo_financiamento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='valor_ambulatorial_sa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='valor_ambulatorial_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='valor_hospitalar_sh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='valor_hospitalar_sp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='valor_hospitalar_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_prontuario', models.CharField(max_length=20, verbose_name='Número do prontuário')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fila_cirurgica.paciente')),
            ],
            options={
                'verbose_name': 'prontuário',
                'verbose_name_plural': 'prontuários',
            },
        ),
    ]
