# Generated by Django 5.1.3 on 2024-12-09 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fila_cirurgica', '0002_remove_paciente_prontuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prontuario',
            name='numero_prontuario',
        ),
        migrations.RemoveField(
            model_name='prontuario',
            name='paciente',
        ),
    ]
