# Generated by Django 5.1.3 on 2024-12-09 16:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila_cirurgica', '0003_remove_prontuario_numero_prontuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prontuario',
            name='data_entrada',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prontuario',
            name='numero_prontuario',
            field=models.CharField(default=1, max_length=20, verbose_name='Número do prontuário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prontuario',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fila_cirurgica.paciente'),
            preserve_default=False,
        ),
    ]
