# Generated by Django 5.1.3 on 2024-12-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila_cirurgica', '0006_listaesperacirurgica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listaesperacirurgica',
            options={'verbose_name': 'Lista de Espera Cirúrgica', 'verbose_name_plural': 'Listas de Espera Cirúrgica'},
        ),
        migrations.AddField(
            model_name='listaesperacirurgica',
            name='pontos',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
