# Generated by Django 5.1.3 on 2025-02-07 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fila_cirurgica', '0007_alter_listaesperacirurgica_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listaesperacirurgica',
            options={'verbose_name': 'Lista de Espera Cirúrgica', 'verbose_name_plural': 'Lista de Espera Cirúrgica'},
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='telefone_contato',
            new_name='telefone_contato_principal',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='telefone_contato2',
            new_name='telefone_contato_secundario',
        ),
    ]
