# Generated by Django 5.1.3 on 2025-02-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila_cirurgica', '0009_alter_paciente_data_nascimento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedimentoSigtap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('origem', models.TextField(blank=True, null=True)),
                ('complexidade', models.CharField(blank=True, max_length=100, null=True)),
                ('modalidades', models.TextField(blank=True, null=True)),
                ('instrumento_registro', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_financiamento', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_ambulatorial_sa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_ambulatorial_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_hospitalar_sp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_hospitalar_sh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_hospitalar_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('atributo_complementar', models.JSONField(blank=True, default=list, null=True)),
                ('sexo', models.CharField(blank=True, max_length=50, null=True)),
                ('idade_minima', models.IntegerField(blank=True, null=True)),
                ('idade_maxima', models.IntegerField(blank=True, null=True)),
                ('quantidade_maxima', models.IntegerField(blank=True, null=True)),
                ('media_permanencia', models.IntegerField(blank=True, null=True)),
                ('pontos', models.IntegerField(blank=True, null=True)),
                ('cbo', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'verbose_name': 'Procedimento',
                'verbose_name_plural': 'Procedimentos',
                'ordering': ['codigo'],
            },
        ),
    ]
