# Generated by Django 5.1.3 on 2025-02-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila_cirurgica', '0010_procedimentosigtap'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedimentoAghu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código do Procedimento')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Procedimento')),
            ],
        ),
    ]
