# Generated by Django 5.1.3 on 2025-02-20 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila_cirurgica', '0011_procedimentoaghu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaesperacirurgica',
            name='procedimentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fila_cirurgica.procedimentoaghu'),
        ),
    ]
