# Generated by Django 5.1.3 on 2025-03-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila_cirurgica', '0012_alter_listaesperacirurgica_procedimentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_especialidade', models.CharField(max_length=10, unique=True)),
                ('nome_especialidade', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='listaesperacirurgica',
            name='situacao',
            field=models.CharField(choices=[('CA', 'CONSULTA AGENDADA'), ('AE', 'EXAMES PENDENTES'), ('DP', 'DOCUMENTAÇÃO PENDENTE'), ('PP', 'PACIENTE PRONTO PARA CIRURGIA'), ('CNR', 'CONTATO NÃO REALIZADO'), ('T1F', 'TENTATIVA 1 FALHOU'), ('T2F', 'TENTATIVA 2 FALHOU'), ('T3F', 'TENTATIVA 3 FALHOU, NÃO SERÃO REALIZADOS NOVOS CONTATOS'), ('CRS', 'CONTATO REALIZADO COM SUCESSO')]),
        ),
    ]
