# Generated by Django 5.1.3 on 2025-03-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila_cirurgica', '0013_especialidade_medico_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medico',
            options={'verbose_name': 'Médico', 'verbose_name_plural': 'Médicos'},
        ),
        migrations.AddField(
            model_name='listaesperacirurgica',
            name='especialidade',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='especialidade'),
        ),
    ]
