# Generated by Django 5.1.3 on 2025-03-07 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila_cirurgica', '0014_alter_medico_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaesperacirurgica',
            name='especialidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fila_cirurgica.especialidade'),
        ),
    ]
