# Generated by Django 5.1.3 on 2025-03-09 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fila_cirurgica', '0015_alter_listaesperacirurgica_especialidade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Procedimento',
        ),
        migrations.AlterModelOptions(
            name='procedimentoaghu',
            options={'verbose_name': 'Procedimento AGHU', 'verbose_name_plural': 'Procedimentos AGHU'},
        ),
        migrations.AlterModelOptions(
            name='procedimentosigtap',
            options={'ordering': ['codigo'], 'verbose_name': 'Procedimento Sigtap', 'verbose_name_plural': 'Procedimentos Sigtap'},
        ),
    ]
