# Generated by Django 5.1.3 on 2025-03-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila_cirurgica', '0016_delete_procedimento_alter_procedimentoaghu_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedimentoaghu',
            options={'verbose_name': 'Procedimento', 'verbose_name_plural': 'Procedimentos'},
        ),
        migrations.AddField(
            model_name='medico',
            name='especialidades',
            field=models.ManyToManyField(to='fila_cirurgica.especialidade'),
        ),
    ]
