# Generated by Django 5.1.3 on 2025-03-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila_cirurgica', '0018_alter_medico_especialidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especialidades',
            field=models.ManyToManyField(blank=True, to='fila_cirurgica.especialidade'),
        ),
    ]
