# Generated by Django 5.1.3 on 2025-03-10 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fila_cirurgica', '0019_alter_medico_especialidades'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listaesperacirurgica',
            options={'ordering': ['data_entrada'], 'verbose_name': 'Lista de Espera Cirúrgica', 'verbose_name_plural': 'Lista de Espera Cirúrgica'},
        ),
        migrations.RemoveField(
            model_name='listaesperacirurgica',
            name='demanda_judicial',
        ),
        migrations.RemoveField(
            model_name='listaesperacirurgica',
            name='especialidade',
        ),
        migrations.RemoveField(
            model_name='listaesperacirurgica',
            name='pontos',
        ),
        migrations.RemoveField(
            model_name='listaesperacirurgica',
            name='prioridade',
        ),
    ]
