# Generated by Django 5.1.3 on 2025-03-10 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fila_cirurgica', '0020_alter_listaesperacirurgica_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listaesperacirurgica',
            old_name='procedimentos',
            new_name='procedimento',
        ),
    ]
