# Generated by Django 5.1.3 on 2025-03-10 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila_cirurgica', '0021_rename_procedimentos_listaesperacirurgica_procedimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaesperacirurgica',
            name='especialidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fila_cirurgica.especialidade'),
        ),
        migrations.AddField(
            model_name='listaesperacirurgica',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fila_cirurgica.medico'),
        ),
    ]
