# Generated by Django 5.1.3 on 2025-03-12 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila_cirurgica', '0022_listaesperacirurgica_especialidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecialidadeProcedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fila_cirurgica.especialidade')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fila_cirurgica.procedimentoaghu')),
            ],
            options={
                'verbose_name': 'Especialidade e Procedimento',
                'verbose_name_plural': 'Especialidades e Procedimentos',
                'unique_together': {('especialidade', 'procedimento')},
            },
        ),
    ]
