# Generated by Django 5.1.3 on 2025-03-13 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila_cirurgica', '0025_remove_listaesperacirurgica_especialidadeprocedimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaesperacirurgica',
            name='especialidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fila_cirurgica.especialidade', verbose_name='Especialidade'),
        ),
        migrations.AlterField(
            model_name='especialidadeprocedimento',
            name='especialidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fila_cirurgica.especialidade', verbose_name='AAA'),
        ),
        migrations.AlterField(
            model_name='listaesperacirurgica',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fila_cirurgica.medico', verbose_name='Médico'),
        ),
        migrations.AlterField(
            model_name='listaesperacirurgica',
            name='observacoes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='listaesperacirurgica',
            name='situacao',
            field=models.CharField(choices=[('CA', 'CONSULTA AGENDADA'), ('AE', 'EXAMES PENDENTES'), ('DP', 'DOCUMENTAÇÃO PENDENTE'), ('PP', 'PACIENTE PRONTO PARA CIRURGIA'), ('CNR', 'CONTATO NÃO REALIZADO'), ('T1F', 'TENTATIVA 1 FALHOU'), ('T2F', 'TENTATIVA 2 FALHOU'), ('T3F', 'TENTATIVA 3 FALHOU, NÃO SERÃO REALIZADOS NOVOS CONTATOS'), ('CRS', 'CONTATO REALIZADO COM SUCESSO')], verbose_name='Situação'),
        ),
    ]
