# Generated by Django 5.1.3 on 2025-03-13 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila_cirurgica', '0026_listaesperacirurgica_especialidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CA', 'CONSULTA AGENDADA'), ('AE', 'EXAMES PENDENTES'), ('DP', 'DOCUMENTAÇÃO PENDENTE'), ('PP', 'PACIENTE PRONTO PARA CIRURGIA'), ('CNR', 'CONTATO NÃO REALIZADO'), ('T1F', 'TENTATIVA 1 FALHOU'), ('T2F', 'TENTATIVA 2 FALHOU'), ('T3F', 'TENTATIVA 3 FALHOU, NÃO SERÃO REALIZADOS NOVOS CONTATOS'), ('CRS', 'CONTATO REALIZADO COM SUCESSO')], max_length=5, unique=True, verbose_name='Situação')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
        ),
        migrations.RemoveField(
            model_name='listaesperacirurgica',
            name='especialidade',
        ),
        migrations.AlterField(
            model_name='especialidadeprocedimento',
            name='especialidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fila_cirurgica.especialidade'),
        ),
        migrations.AlterField(
            model_name='listaesperacirurgica',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fila_cirurgica.medico'),
        ),
        migrations.AlterField(
            model_name='listaesperacirurgica',
            name='observacoes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='observações'),
        ),
        migrations.AlterField(
            model_name='listaesperacirurgica',
            name='situacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fila_cirurgica.situacao'),
        ),
    ]
