# Generated by Django 5.1.3 on 2025-03-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila_cirurgica', '0027_situacao_remove_listaesperacirurgica_especialidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaesperacirurgica',
            name='situacao',
            field=models.CharField(choices=[('CA', 'CONSULTA AGENDADA'), ('AE', 'EXAMES PENDENTES'), ('DP', 'DOCUMENTAÇÃO PENDENTE'), ('PP', 'PACIENTE PRONTO PARA CIRURGIA'), ('CNR', 'CONTATO NÃO REALIZADO'), ('T1F', 'TENTATIVA 1 FALHOU'), ('T2F', 'TENTATIVA 2 FALHOU'), ('T3F', 'TENTATIVA 3 FALHOU, NÃO SERÃO REALIZADOS NOVOS CONTATOS'), ('CRS', 'CONTATO REALIZADO COM SUCESSO')], verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='listaesperacirurgica',
            name='data_novo_contato',
            field=models.DateField(blank=True, null=True, verbose_name='Data para novo contato'),
        ),
        migrations.DeleteModel(
            name='Situacao',
        ),
    ]
