# Generated by Django 5.1.3 on 2025-03-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila_cirurgica', '0029_historicallistaesperacirurgica'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallistaesperacirurgica',
            name='medida_judicial',
            field=models.BooleanField(default=False, null=True, verbose_name='Medida Judicial'),
        ),
        migrations.AddField(
            model_name='historicallistaesperacirurgica',
            name='paciente_oncologico',
            field=models.BooleanField(default=False, null=True, verbose_name='Paciente Oncológico'),
        ),
        migrations.AddField(
            model_name='historicallistaesperacirurgica',
            name='urgencia',
            field=models.BooleanField(default=False, null=True, verbose_name='Urgência'),
        ),
        migrations.AddField(
            model_name='listaesperacirurgica',
            name='medida_judicial',
            field=models.BooleanField(default=False, null=True, verbose_name='Medida Judicial'),
        ),
        migrations.AddField(
            model_name='listaesperacirurgica',
            name='paciente_oncologico',
            field=models.BooleanField(default=False, null=True, verbose_name='Paciente Oncológico'),
        ),
        migrations.AddField(
            model_name='listaesperacirurgica',
            name='urgencia',
            field=models.BooleanField(default=False, null=True, verbose_name='Urgência'),
        ),
    ]
