# Generated by Django 5.1.3 on 2025-04-01 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila_cirurgica', '0030_historicallistaesperacirurgica_medida_judicial_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listaesperacirurgica',
            options={'verbose_name': 'Lista de Espera Cirúrgica', 'verbose_name_plural': 'Lista de Espera Cirúrgica'},
        ),
        migrations.AddField(
            model_name='historicallistaesperacirurgica',
            name='especialidade',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fila_cirurgica.especialidade'),
        ),
        migrations.AddField(
            model_name='listaesperacirurgica',
            name='especialidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fila_cirurgica.especialidade'),
        ),
    ]
