# Generated by Django 5.1.3 on 2025-04-01 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fila_cirurgica', '0031_alter_listaesperacirurgica_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallistaesperacirurgica',
            name='especialidade',
        ),
        migrations.RemoveField(
            model_name='listaesperacirurgica',
            name='especialidade',
        ),
    ]
