# Generated by Django 5.1.3 on 2025-05-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila_cirurgica', '0032_remove_historicallistaesperacirurgica_especialidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidade',
            name='demanda_pedagogica',
            field=models.BooleanField(default=False, null=True, verbose_name='Demanda Pedagógica'),
        ),
    ]
