# Generated by Django 5.1.3 on 2025-05-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila_cirurgica', '0033_especialidade_demanda_pedagogica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallistaesperacirurgica',
            name='paciente_oncologico',
        ),
        migrations.RemoveField(
            model_name='historicallistaesperacirurgica',
            name='urgencia',
        ),
        migrations.RemoveField(
            model_name='listaesperacirurgica',
            name='paciente_oncologico',
        ),
        migrations.RemoveField(
            model_name='listaesperacirurgica',
            name='urgencia',
        ),
        migrations.AddField(
            model_name='historicallistaesperacirurgica',
            name='prioridade',
            field=models.CharField(choices=[('ONC', 'Paciente Oncológico'), ('BRE', 'Com Brevidade'), ('SEM', 'Sem Brevidade')], default='SEM', max_length=3, verbose_name='Tipo de Prioridade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listaesperacirurgica',
            name='prioridade',
            field=models.CharField(choices=[('ONC', 'Paciente Oncológico'), ('BRE', 'Com Brevidade'), ('SEM', 'Sem Brevidade')], default='SEM', max_length=3, verbose_name='Tipo de Prioridade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicallistaesperacirurgica',
            name='observacoes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='listaesperacirurgica',
            name='observacoes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone_contato_secundario',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone secundário'),
        ),
    ]
