# Generated by Django 5.1.3 on 2025-05-20 14:31

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila_cirurgica', '0034_remove_historicallistaesperacirurgica_paciente_oncologico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadorEspecialidade',
            fields=[
            ],
            options={
                'verbose_name': 'Indicadores de Especialidades',
                'verbose_name_plural': 'Indicadores de Especialidades',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fila_cirurgica.listaesperacirurgica',),
        ),
        migrations.AddField(
            model_name='historicallistaesperacirurgica',
            name='especialidade',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fila_cirurgica.especialidade'),
        ),
        migrations.AddField(
            model_name='listaesperacirurgica',
            name='especialidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fila_cirurgica.especialidade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicallistaesperacirurgica',
            name='prioridade',
            field=models.CharField(choices=[('ONC', 'Paciente Oncológico'), ('BRE', 'Com Brevidade'), ('SEM', 'Sem Brevidade')], default='SEM', max_length=3),
        ),
        migrations.AlterField(
            model_name='listaesperacirurgica',
            name='prioridade',
            field=models.CharField(choices=[('ONC', 'Paciente Oncológico'), ('BRE', 'Com Brevidade'), ('SEM', 'Sem Brevidade')], default='SEM', max_length=3),
        ),
        migrations.AlterField(
            model_name='listaesperacirurgica',
            name='procedimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fila_cirurgica.procedimentoaghu'),
        ),
        migrations.CreateModel(
            name='HistoricalIndicadorEspecialidade',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(blank=True, editable=False)),
                ('prioridade', models.CharField(choices=[('ONC', 'Paciente Oncológico'), ('BRE', 'Com Brevidade'), ('SEM', 'Sem Brevidade')], default='SEM', max_length=3)),
                ('medida_judicial', models.BooleanField(default=False, null=True, verbose_name='Medida Judicial')),
                ('situacao', models.CharField(choices=[('CA', 'CONSULTA AGENDADA'), ('AE', 'EXAMES PENDENTES'), ('DP', 'DOCUMENTAÇÃO PENDENTE'), ('PP', 'PACIENTE PRONTO PARA CIRURGIA'), ('CNR', 'CONTATO NÃO REALIZADO'), ('T1F', 'TENTATIVA 1 FALHOU'), ('T2F', 'TENTATIVA 2 FALHOU'), ('T3F', 'TENTATIVA 3 FALHOU, NÃO SERÃO REALIZADOS NOVOS CONTATOS'), ('CRS', 'CONTATO REALIZADO COM SUCESSO')], verbose_name='Situação')),
                ('observacoes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observações')),
                ('data_novo_contato', models.DateField(blank=True, null=True, verbose_name='Data para novo contato')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('especialidade', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fila_cirurgica.especialidade')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('medico', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fila_cirurgica.medico')),
                ('paciente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fila_cirurgica.paciente')),
                ('procedimento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fila_cirurgica.procedimentoaghu')),
            ],
            options={
                'verbose_name': 'historical Indicadores de Especialidades',
                'verbose_name_plural': 'historical Indicadores de Especialidades',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
