# Generated by Django 5.1.3 on 2025-06-04 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila_cirurgica', '0035_indicadorespecialidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalindicadorespecialidade',
            name='campanha',
            field=models.BooleanField(default=False, null=True, verbose_name='Participa de campanha'),
        ),
        migrations.AddField(
            model_name='historicallistaesperacirurgica',
            name='campanha',
            field=models.BooleanField(default=False, null=True, verbose_name='Participa de campanha'),
        ),
        migrations.AddField(
            model_name='listaesperacirurgica',
            name='campanha',
            field=models.BooleanField(default=False, null=True, verbose_name='Participa de campanha'),
        ),
        migrations.AlterField(
            model_name='historicalindicadorespecialidade',
            name='medico',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fila_cirurgica.medico', verbose_name='Médico'),
        ),
        migrations.AlterField(
            model_name='historicallistaesperacirurgica',
            name='medico',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fila_cirurgica.medico', verbose_name='Médico'),
        ),
        migrations.AlterField(
            model_name='listaesperacirurgica',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fila_cirurgica.medico', verbose_name='Médico'),
        ),
    ]
