# Generated by Django 5.1.3 on 2025-06-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila_cirurgica', '0036_historicalindicadorespecialidade_campanha_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalindicadorespecialidade',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'Histórico de Lista de Espera Cirúrgica', 'verbose_name_plural': 'historical Indicadores de Especialidades'},
        ),
        migrations.AlterModelOptions(
            name='historicallistaesperacirurgica',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'Histórico de Lista de Espera Cirúrgica', 'verbose_name_plural': 'historical Lista de Espera Cirúrgica'},
        ),
        migrations.RemoveField(
            model_name='historicalindicadorespecialidade',
            name='campanha',
        ),
        migrations.RemoveField(
            model_name='historicallistaesperacirurgica',
            name='campanha',
        ),
        migrations.RemoveField(
            model_name='listaesperacirurgica',
            name='campanha',
        ),
        migrations.AlterField(
            model_name='historicalindicadorespecialidade',
            name='history_change_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da alteração'),
        ),
        migrations.AlterField(
            model_name='historicallistaesperacirurgica',
            name='history_change_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da alteração'),
        ),
    ]
