# Generated by Django 5.2.1 on 2025-06-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila_cirurgica', '0037_alter_historicalindicadorespecialidade_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalindicadorespecialidade',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Está ativo na fila?'),
        ),
        migrations.AddField(
            model_name='historicalindicadorespecialidade',
            name='motivo_saida',
            field=models.CharField(blank=True, choices=[('MORTE', 'Paciente faleceu'), ('OUTRO_LOCAL', 'Cirurgia realizada em outro local'), ('AUTOEXCLUSAO', 'Paciente solicitou autoexclusão da fila')], max_length=20, null=True, verbose_name='Motivo da saída da fila'),
        ),
        migrations.AddField(
            model_name='historicallistaesperacirurgica',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Está ativo na fila?'),
        ),
        migrations.AddField(
            model_name='historicallistaesperacirurgica',
            name='motivo_saida',
            field=models.CharField(blank=True, choices=[('MORTE', 'Paciente faleceu'), ('OUTRO_LOCAL', 'Cirurgia realizada em outro local'), ('AUTOEXCLUSAO', 'Paciente solicitou autoexclusão da fila')], max_length=20, null=True, verbose_name='Motivo da saída da fila'),
        ),
        migrations.AddField(
            model_name='listaesperacirurgica',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Está ativo na fila?'),
        ),
        migrations.AddField(
            model_name='listaesperacirurgica',
            name='motivo_saida',
            field=models.CharField(blank=True, choices=[('MORTE', 'Paciente faleceu'), ('OUTRO_LOCAL', 'Cirurgia realizada em outro local'), ('AUTOEXCLUSAO', 'Paciente solicitou autoexclusão da fila')], max_length=20, null=True, verbose_name='Motivo da saída da fila'),
        ),
    ]
